---
namespace: ansible
name: mysql
version: 5.1.0
readme: README.md
authors:
  - Ansible community
description: MySQL and MariaDB collection for Ansible
license_file: COPYING
tags:
  - database
  - mysql
  - mariadb
repository: https://github.com/ansible-collections/ansible.mysql
documentation: https://github.com/ansible-collections/ansible.mysql
homepage: https://github.com/ansible-collections/ansible.mysql
issues: https://github.com/ansible-collections/ansible.mysql/issues
build_ignore:
  - .vscode
  - tests/integration
  - tests/unit
  - changelogs/.plugin-cache.yaml
  - .github
  - .agents
  - .cursor
  - .claude
  - .gitignore
  - .venv
